### ISSUE TITLE
Launches remain in progress from Postman if you have more than a single string for a name.

### ISSUE THREAD

**Issue by dantench** [reportportal/agent-js-postman#63] opened 2021-09-22 14:21 UTC
When running with tests in postman like this:

`pm.test("StoryID:" + request.name + " Response status is 200", function () {
    pm.response.to.have.status(200);
});`

Then the launch / items remain in progress forever and no results are ever logged

![image](https://user-images.githubusercontent.com/29710317/134360953-eeb64a82-aad3-42c4-8053-97cfb05f4b56.png)

When we switched to:

`pm.test("StoryID: Response status is 200", function () {
    pm.response.to.have.status(200);
});`

Then it started working:

![image](https://user-images.githubusercontent.com/29710317/134361221-c7a0b178-b517-4b96-8f0a-d705edaff698.png)

There were no logs... or helpful information to determine this problem, it took several days of trial and error to find this issue. The request.name function in Postman literally just inserts the name of the request being made. This is there to make the names of the tests unique to solve an issue with the Junit parser in Bamboo. 

We have a choice of incorrect results in bamboo and it working in Report portal. Correct results in bamboo and no results in report portal, or hard coding a unique name in our test suite and both work, but we introduce bad practice. We also tried creating a unique name as a variable and then passing in the variable string to the test name... report portal didn't like that either.

**Comment by dantench** [comment] 2021-09-23 09:54
See: https://github.com/reportportal/agent-js-postman/issues/60 I believe they are the same issue.

**Comment by AmsterGet** [comment] 2022-02-25 14:09
Closed as duplicate of https://github.com/reportportal/agent-js-postman/issues/60

**Closed by AmsterGet** 2022-02-25 14:09 UTC
Labels: duplicate
