### ISSUE TITLE
Cannot read property 'requestError' of undefined and RP lunch is not ending

### ISSUE THREAD

**Issue by RuggeriLuca** [reportportal/agent-js-postman#8] opened 2019-06-02 19:59 UTC
Hello , 
i'm running newman.run using the below script. 
all work fine if the collect does not have error. but if there are some error i take the error :

`Success start item hxq44kjwfcy0t6
Success start item hxq44kjwfcy0t7
Success start item hxq44kjwfcy0un
Start test item hxq44kjwfcy0vd
Start test item hxq44kjwfcy1ab
Start test item hxq44kjwfcy1f7
C:\Runs\Postman\node_modules\@reportportal\newman-reporter-reportportal\lib\index.js:260
        if (execution.requestError) {
                     ^

TypeError: Cannot read property 'requestError' of undefined
    at finishSteps (C:\Runs\Postman\node_modules\@reportportal\newman-reporter-reportportal\lib\index.js:260:22)
    at EventEmitter.emitter.on (C:\Runs\Postman\node_modules\@reportportal\newman-reporter-reportportal\lib\index.js:175:13)
    at EventEmitter.emit (C:\Runs\Postman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Runs\Postman\node_modules\newman\lib\run\index.js:278:29)
    at C:\Runs\Postman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Runs\Postman\node_modules\postman-runtime\lib\runner\run.js:163:13)
    at PostmanCollectionRun.<anonymous> (C:\Runs\Postman\node_modules\postman-runtime\lib\runner\run.js:169:76)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

C:\Runs\Postman>`

`  newmanLocalRun: function(collections,gameId,reportPath,reportTemplate,mainLogName,logsPath)
  {
	    var newman = require('newman');
		var async = require('async'); // https://npmjs.org/package/async
		
		module.exports.BKFiles(logsPath,mainLogName,logsPath,mainLogName,true)
		
async.eachSeries(collections, function(iteam, next)
    {
      console.log('START ---> ' + iteam.runName + ': ' + iteam.iterationData);
      if (iteam.type === 1)
      {
        //if exists previus log save it addind date
        module.exports.BKFiles(logsPath, iteam.dataLoggingFile, logsPath, iteam.dataLoggingFile, true);
      }
      var myglobal = JSON.parse(fs.readFileSync(iteam.globals.toString(), 'utf8'));
      if (iteam.configGenerateData != undefined)
      {
        Object.keys(iteam.configGenerateData).forEach(function(key)
        {
          myglobal.values.push(iteam.configGenerateData[key])
        });
      }
      var d = new Date();
      d = d.getFullYear().toString() + ('0' + (d.getMonth() + 1)).slice(-2).toString() + ('0' + d.getDate()).slice(-2).toString() + "_" + ('0' + d.getHours()).slice(-2).toString() + ('0' + d.getMinutes()).slice(-2).toString() + ('0' + d.getSeconds()).slice(-2).toString();
      var dataObject = "";
      if (iteam.iterationData !== undefined)
      {
        dataObject = iteam.iterationData;
      }
      else
      {
        dataObject = null;
      }
      newman.run(
          {
            collection: iteam.collection,
            environment: iteam.environment,
            exportEnvironment: iteam.exportEnvironment,
            globals: myglobal,
            iterationCount: iteam.iterationCount,
            iterationData: dataObject,
            folder: iteam.folder,
			bail: true,
            insecure: true,
            stopOnError: true,
			reporters: "@reportportal/reportportal",
			reporter: {
            "@reportportal/reportportal": {
                debug: true,
                endpoint: "https://web.demo.reportportal.io/api/v1",
                token: "d879dd28-da0d-4772-a4ce-c91e6491ec1d",
                launch: "LAUNCH_NAME",
                project: "RUGGERILUCA_PERSONAL"
            }
            //reporters: iteam.reporters,
            //reporter:
            //{
            //  htmlextra:
             // {
             //   export: (reportPath + gameId + '_' + iteam.runName.replace(' ', '_') + '_' + d + '.Html'), // If not specified, the file will be written to `newman/` in the current working directory.
             //   template: reportTemplate, // optional, the default template will be used if one is not specified
             //   title: iteam.runName
			//	showOnlyFails: true
            //  }
            }
          }, function(err, summary)
          {
            if (iteam.type === 1)
            {
              module.exports.BKFiles(logsPath, mainLogName, logsPath, iteam.dataLoggingFile, false)
            }
            console.log('END   ---> ' + iteam.runName);
            next(err, summary);
          });
        },
        function(err, results)
        {
          // process the errors/results here
        });
  
}
}`

**Comment by RuggeriLuca** [comment] 2019-06-02 21:05
Hello , 
i found my issues in my Postman API call script i have a some programmatically call to other end point ... 
is this supported ?

**Comment by groov1kk** [comment] 2019-06-20 14:53
Hello

What kind of error you expect? Is it verification error? Or script error?

**Comment by groov1kk** [comment] 2019-06-21 09:26
Actually, this reporter doesn't support test cases which perform http requests. There is a bug in newman that doesn't provide to resolve such cases correctly

**Comment by 03-triple-threat** [comment] 2019-09-05 21:27
Hello,

Has there been any updates on this issue? Also, does utilizing OAuth2 in the collection affect this? I have multiple collections that do not use OAuth2 which are being reported correctly. The one collection that I do use OAuth2 runs into the originally posted issue.

**Comment by groov1kk** [comment] 2019-09-08 20:05
Hello

Bug is still (opened)[https://github.com/postmanlabs/newman/issues/1868]

**Comment by murdoc-mos** [comment] 2019-10-11 19:22
I hit this same issue with:

`if [[ -z $1 ]]; then
    mkdir -p "${WORK_DIR}"
    mkdir -p "${ENV}"

    newman run "${POSTMAN_DIR}/ci-tb.postman_collection.json" --environment "${POSTMAN_DIR}/ci-envbvt.postman_environment.json" \
            --reporters "htmlextra,reportportal" --reporter-htmlextra-export "${WORK_DIR}/ci-tb-result.html" \
            --reporter-reportportal-debug=true \
            --reporter-reportportal-endpoint=${RP_ENDPOINT} \
            --reporter-reportportal-token=${RP_TOKEN} \
            --reporter-reportportal-launch=PayFac Integration Tests \
            --reporter-reportportal-project=payment_services \
            -x \
            --export-environment "${ENV}" 
else
    env_file=$(ls ${ENV})
    newman run "${POSTMAN_DIR}/$1.postman_collection.json" --environment "${ENV}/${env_file}" \
            --reporters "htmlextra,reportportal" --reporter-htmlextra-export "${WORK_DIR}/$1-result.html" \
            --reporter-reportportal-debug=true \
            --reporter-reportportal-endpoint=${RP_ENDPOINT} \
            --reporter-reportportal-token=${RP_TOKEN} \
            --reporter-reportportal-launch=PayFac Integration Tests \
            --reporter-reportportal-project=payment_services \
            --suppress-exit-code
fi
exit 0`

**Comment by Gageonea** [comment] 2019-12-04 10:01
Hello. I can still see the issue is open, but do we have any updates on this, or did anybody at least find a workaround?

**Comment by quiquetubi** [comment] 2020-02-13 18:59
Hello, I do need to use a `pm.sendRequest()` inside my tests. Is this issue still open? Is there any workaround to solve this?

**Comment by quiquetubi** [comment] 2020-02-18 15:26
So an update of this is the following:

- The postman agent hasn't been updated yet.
- There are some dev guides about async reporting. That we can use to add this improvement by  ourselves:
    Difference between API ver 4/5: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/api-differences.md#launch-asynchronous-controller 
    Async mechanism  https://github.com/reportportal/documentation/blob/async-reporting/src/md/src/DevGuides/async-reporting.md
- We can wait until the team updates it.
- I've been trying to make my async calls in my testing synchronous by using promises, async and await. Maybe that could be a workaround for the time being.

I'm not really an expert with agents and how they work, so if anyone has done the modifications already to the code in order to accept async calls I would be more than grateful if you share it :)

**Comment by sammy1431** [comment] 2020-02-20 16:44
I am also stuck with this error. It would be nice if someone could address this issue and put out a new version.

**Comment by davadora** [comment] 2021-02-04 02:38
> Actually, this reporter doesn't support test cases which perform http requests. There is a bug in newman that doesn't provide to resolve such cases correctly

Is there a reference to the bug in Newman that can be cited for followup with their developers?  I see that Newman v5 was released in 2020.  We are experiencing this issue as well, and it appears yet to be resolved.  Would it be possible to clarify what is believed to be root cause?  (Newman, or RP)?

**Comment by Christopher-Kane** [comment] 2021-02-04 22:58
I am also running into this same issue, I'm not entirely sure what can be done to fix it at this point since I believe I have followed all appropriate guidance I could find. @groov1kk Is there anyway we could get some priority on this issue or start a conversation around understanding it more and exactly why it happens and what causes it? This is currently blocking for what I'd like to complete and have pretty much hit a wall. Thanks!

**Comment by Christopher-Kane** [comment] 2021-02-18 18:57
> Hello
> 
> Bug is still [opened](https://github.com/postmanlabs/newman/issues/1868)

What exactly is this bug preventing from occurring in report portal? Could you expand or explain that a bit more?

**Comment by davadora** [comment] 2021-03-30 20:17
with the recent release of v5.0.0, is it safe to assume that this is still unresolved?  We're considering a RP upgrade to the latest based on their social media mention of POSTman support.

**Comment by AmsterGet** [comment] 2021-08-30 16:23
Hi guys!
We've already have the version 5.0.2 which provides new reporting compatible with RP version 5.*.
I'll close this issue but feel free to open it again if you have any other questions on the topic.

**Closed by AmsterGet** 2021-08-30 16:23 UTC
Labels: bug
